import asyncio
from abc import abstractmethod
import sqlite3
from pathlib import Path

from pydantic import AwareDatetime, PrivateAttr

from modulon.events import AbstractEvent, event_from_json
from modulon.graph import AbstractFactory, requires
from modulon.utils import JsonlFilePath


@requires("event.sender")
class AbstractEventReplayer(AbstractFactory, node_namespace="event.replayer"):
    """
    An `event.replayer` emits events at runtime from a list loaded at setup. The
    events are sorted and emitted in ascending order according to their original `.as_of`
    time.
    """

    _events: list[AbstractEvent] = PrivateAttr()

    async def _setup(self) -> None:
        """Load events and initialize senders prior to firing"""
        self.log.info("Loading events")
        self._events = await self._load_events()

        self.log.info("Sorting %d event(s)", len(self._events))
        self._events.sort(key=lambda ev: ev.as_of)

        event_types = {type(event) for event in self._events}
        self.log.info("Ensuring event senders are ready for types: %s", event_types)
        async with asyncio.TaskGroup() as tg:
            _ = [
                tg.create_task(self.dep.event.sender(event_type))
                for event_type in event_types
            ]

    async def _run(self) -> None:
        """Fire events in sorted order"""
        self.log.info("Event replay starting")
        last_event_time: AwareDatetime | None = None
        for i, event in enumerate(self._events, start=1):
            sender = await self.dep.event.sender(type(event))
            if last_event_time is not None:
                delta = event.as_of - last_event_time
                await asyncio.sleep(delta.total_seconds())

            self.log.info("Replaying event %d/%d", i, len(self._events))
            await sender.send(event)
            last_event_time = event.as_of

        self.log.info("Event replay complete")

    @abstractmethod
    async def _load_events(self) -> list[AbstractEvent]: ...


class ConfigEventReplayer(AbstractEventReplayer):
    """
    This event replayer loads events specified via the config.
    """

    events: list[AbstractEvent]

    async def _load_events(self) -> list[AbstractEvent]:
        return self.events


class JsonlFileEventReplayer(AbstractEventReplayer):
    """
    This event replayer loads events specified via a .jsonl file.

    A valid file can be generated by `event.archiver.JsonlFileEventArchiver`.
    """

    fpath: JsonlFilePath

    async def _load_events(self) -> list[AbstractEvent]:
        with self.fpath.open("r") as fp:
            events = [event_from_json(line) for line in fp.readlines() if line.strip()]
        return events


class SQLiteEventReplayer(AbstractEventReplayer):
    """
    This event replayer loads events from a SQLite database written by
    `event.archiver.SQLiteEventArchiver`.
    """

    db_path: Path
    event_query: str = """
    SELECT json(data)
    FROM events
    ORDER BY as_of
    """

    async def _load_events(self) -> list[AbstractEvent]:
        conn = sqlite3.connect(self.db_path)
        try:
            cursor = conn.execute(self.event_query)
            return [event_from_json(row[0]) for row in cursor.fetchall()]
        finally:
            conn.close()
